server:
  port: 8888

#sevice :

#logging:
#  level:
#    org.springframework.boot: INFO
#    org.springframework.web : DEBUG
#    org.springframework.data : INFO  

spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb;MODE=Mysql;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
  jpa:
    show-sql: true
    hibernate: 
      ddl-auto: create-drop
      
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp      

application:
  mybatis:
    config-location: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:mybatis/mapper/*.xml
    type-aliases-package: com.study.domain
  security:
    salt: sha_salt

---

spring:
  profiles : dev
  datasource:
    platform: mysql
    initialize: false
    data: data-mysql.sql
    url: jdbc:mysql://localhost:3306/cnu?useUnicode=true&amp;characterEncoding=UTF8&amp;characterSetResult=UTF8&amp;jdbcCompliantTruncation=false&amp;connectTimeout=60000&amp;sockTimeout=60000&amp;zeroDateTimeBehavior=convertToNull
    username: root
    password: platform
    driver-class-name: com.mysql.jdbc.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#
#logging:
#  level:
#    org.springframework.web : INFO
