server:
  port: 8080

#sevice :

#logging:
#  level:
#    org.springframework.boot: INFO
#    org.springframework.web : DEBUG
#    org.springframework.data : INFO  

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp      
      
---

#spring:
#  profiles : server
#  #datasource:
#    #url: jdbc:h2:tcp://localhost/~/handsonlab;MVCC=TRUE
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#
#logging:
#  level:
#    org.springframework.web : INFO
  